sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libeigen3-dev

language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug


script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j
  - make test
